// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// unit_test_soma
List unit_test_soma(int function_id, int seed, double pathLength, double step, double PRT, int popSize, int nDirections, double migrations, double minDiv, int dims);
RcppExport SEXP _dbrpart_unit_test_soma(SEXP function_idSEXP, SEXP seedSEXP, SEXP pathLengthSEXP, SEXP stepSEXP, SEXP PRTSEXP, SEXP popSizeSEXP, SEXP nDirectionsSEXP, SEXP migrationsSEXP, SEXP minDivSEXP, SEXP dimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type function_id(function_idSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< double >::type pathLength(pathLengthSEXP);
    Rcpp::traits::input_parameter< double >::type step(stepSEXP);
    Rcpp::traits::input_parameter< double >::type PRT(PRTSEXP);
    Rcpp::traits::input_parameter< int >::type popSize(popSizeSEXP);
    Rcpp::traits::input_parameter< int >::type nDirections(nDirectionsSEXP);
    Rcpp::traits::input_parameter< double >::type migrations(migrationsSEXP);
    Rcpp::traits::input_parameter< double >::type minDiv(minDivSEXP);
    Rcpp::traits::input_parameter< int >::type dims(dimsSEXP);
    rcpp_result_gen = Rcpp::wrap(unit_test_soma(function_id, seed, pathLength, step, PRT, popSize, nDirections, migrations, minDiv, dims));
    return rcpp_result_gen;
END_RCPP
}
// fit_dbrpart
List fit_dbrpart(IntegerVector in_target_discrete, NumericVector in_target_continuous, NumericMatrix in_target_distance, List in_factorList, List in_numericList, List in_distanceList, List in_distanceCombinations, double in_combinationPower, NumericVector in_acceptable_error, int in_mode, int in_stopMethod, int in_nSims, double in_signifLevel, IntegerVector in_fold, int in_nCategories, NumericVector in_priors, NumericMatrix in_loss, int in_minSplit, int in_minBucket, int in_maxDepth, bool in_alteredPriors, int in_trace, int in_classMethod, int in_pCenters, double soma_pathLength, double soma_step, double soma_PRT, double soma_popSize, int soma_nDirections, int soma_migrations, double soma_minDiv, int soma_seed);
RcppExport SEXP _dbrpart_fit_dbrpart(SEXP in_target_discreteSEXP, SEXP in_target_continuousSEXP, SEXP in_target_distanceSEXP, SEXP in_factorListSEXP, SEXP in_numericListSEXP, SEXP in_distanceListSEXP, SEXP in_distanceCombinationsSEXP, SEXP in_combinationPowerSEXP, SEXP in_acceptable_errorSEXP, SEXP in_modeSEXP, SEXP in_stopMethodSEXP, SEXP in_nSimsSEXP, SEXP in_signifLevelSEXP, SEXP in_foldSEXP, SEXP in_nCategoriesSEXP, SEXP in_priorsSEXP, SEXP in_lossSEXP, SEXP in_minSplitSEXP, SEXP in_minBucketSEXP, SEXP in_maxDepthSEXP, SEXP in_alteredPriorsSEXP, SEXP in_traceSEXP, SEXP in_classMethodSEXP, SEXP in_pCentersSEXP, SEXP soma_pathLengthSEXP, SEXP soma_stepSEXP, SEXP soma_PRTSEXP, SEXP soma_popSizeSEXP, SEXP soma_nDirectionsSEXP, SEXP soma_migrationsSEXP, SEXP soma_minDivSEXP, SEXP soma_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type in_target_discrete(in_target_discreteSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type in_target_continuous(in_target_continuousSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type in_target_distance(in_target_distanceSEXP);
    Rcpp::traits::input_parameter< List >::type in_factorList(in_factorListSEXP);
    Rcpp::traits::input_parameter< List >::type in_numericList(in_numericListSEXP);
    Rcpp::traits::input_parameter< List >::type in_distanceList(in_distanceListSEXP);
    Rcpp::traits::input_parameter< List >::type in_distanceCombinations(in_distanceCombinationsSEXP);
    Rcpp::traits::input_parameter< double >::type in_combinationPower(in_combinationPowerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type in_acceptable_error(in_acceptable_errorSEXP);
    Rcpp::traits::input_parameter< int >::type in_mode(in_modeSEXP);
    Rcpp::traits::input_parameter< int >::type in_stopMethod(in_stopMethodSEXP);
    Rcpp::traits::input_parameter< int >::type in_nSims(in_nSimsSEXP);
    Rcpp::traits::input_parameter< double >::type in_signifLevel(in_signifLevelSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type in_fold(in_foldSEXP);
    Rcpp::traits::input_parameter< int >::type in_nCategories(in_nCategoriesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type in_priors(in_priorsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type in_loss(in_lossSEXP);
    Rcpp::traits::input_parameter< int >::type in_minSplit(in_minSplitSEXP);
    Rcpp::traits::input_parameter< int >::type in_minBucket(in_minBucketSEXP);
    Rcpp::traits::input_parameter< int >::type in_maxDepth(in_maxDepthSEXP);
    Rcpp::traits::input_parameter< bool >::type in_alteredPriors(in_alteredPriorsSEXP);
    Rcpp::traits::input_parameter< int >::type in_trace(in_traceSEXP);
    Rcpp::traits::input_parameter< int >::type in_classMethod(in_classMethodSEXP);
    Rcpp::traits::input_parameter< int >::type in_pCenters(in_pCentersSEXP);
    Rcpp::traits::input_parameter< double >::type soma_pathLength(soma_pathLengthSEXP);
    Rcpp::traits::input_parameter< double >::type soma_step(soma_stepSEXP);
    Rcpp::traits::input_parameter< double >::type soma_PRT(soma_PRTSEXP);
    Rcpp::traits::input_parameter< double >::type soma_popSize(soma_popSizeSEXP);
    Rcpp::traits::input_parameter< int >::type soma_nDirections(soma_nDirectionsSEXP);
    Rcpp::traits::input_parameter< int >::type soma_migrations(soma_migrationsSEXP);
    Rcpp::traits::input_parameter< double >::type soma_minDiv(soma_minDivSEXP);
    Rcpp::traits::input_parameter< int >::type soma_seed(soma_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_dbrpart(in_target_discrete, in_target_continuous, in_target_distance, in_factorList, in_numericList, in_distanceList, in_distanceCombinations, in_combinationPower, in_acceptable_error, in_mode, in_stopMethod, in_nSims, in_signifLevel, in_fold, in_nCategories, in_priors, in_loss, in_minSplit, in_minBucket, in_maxDepth, in_alteredPriors, in_trace, in_classMethod, in_pCenters, soma_pathLength, soma_step, soma_PRT, soma_popSize, soma_nDirections, soma_migrations, soma_minDiv, soma_seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dbrpart_unit_test_soma", (DL_FUNC) &_dbrpart_unit_test_soma, 10},
    {"_dbrpart_fit_dbrpart", (DL_FUNC) &_dbrpart_fit_dbrpart, 32},
    {NULL, NULL, 0}
};

RcppExport void R_init_dbrpart(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
