# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

unit_test_soma <- function(function_id, seed, pathLength, step, PRT, popSize, nDirections, migrations, minDiv, dims) {
    .Call(`_dbrpart_unit_test_soma`, function_id, seed, pathLength, step, PRT, popSize, nDirections, migrations, minDiv, dims)
}

fit_dbrpart <- function(in_target_discrete, in_target_continuous, in_target_distance, in_factorList, in_numericList, in_distanceList, in_distanceCombinations, in_combinationPower, in_acceptable_error, in_mode, in_stopMethod, in_nSims, in_signifLevel, in_fold, in_nCategories, in_priors, in_loss, in_minSplit, in_minBucket, in_maxDepth, in_alteredPriors, in_trace, in_classMethod, in_pCenters, soma_pathLength, soma_step, soma_PRT, soma_popSize, soma_nDirections, soma_migrations, soma_minDiv, soma_seed) {
    .Call(`_dbrpart_fit_dbrpart`, in_target_discrete, in_target_continuous, in_target_distance, in_factorList, in_numericList, in_distanceList, in_distanceCombinations, in_combinationPower, in_acceptable_error, in_mode, in_stopMethod, in_nSims, in_signifLevel, in_fold, in_nCategories, in_priors, in_loss, in_minSplit, in_minBucket, in_maxDepth, in_alteredPriors, in_trace, in_classMethod, in_pCenters, soma_pathLength, soma_step, soma_PRT, soma_popSize, soma_nDirections, soma_migrations, soma_minDiv, soma_seed)
}

